opt_in_rules:
  - attributes
  - closure_spacing
  - empty_count
  - fatal_error_message
  - file_name
  - first_where
  - force_unwrapping
  - identifier_name
  - trailing_whitespace
  - todo
  - nesting
  - redundant_optional_initialization
  - unused_closure_parameter

disabled_rules:
  - force_cast
  - redundant_discardable_let
  - empty_enum_arguments

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 12
  error: 25

file_name: 
  excluded: ["Utils.swift"]

included:
  - this-day/this-day

excluded:
  - .build
  - Packages